development:
  :address: smtp.gmail.com
  :domain: gmail.com
  :port: 587
  :authentication: plain
  :user_name: mfpiccolo@gmail.com
  :password: michaelp
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: xxx
  :password: yyy
  :enable_starttls_auto: true
